language: ruby

cache: bundler

rvm:
  - 2.0.0
  - 2.1.1

env:
  - DB=sqlite

before_script:

script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test

notifications:
  slack: braingourmets:6U5iEUIyYbo0ghwj0kJJygIG
