sudo: false

language: ruby

cache: bundler

rvm:
  - 2.3.0

env:
  - DB=sqlite

before_script:
  - gem install brakeman
  - cp config/local_env_travis.yml config/local_env.yml
  - bundle exec rake db:setup RAILS_ENV=test

script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
  - bundle exec rake assets:precompile RAILS_ENV=test
  - brakeman -z -4
