sudo: false

language: ruby

cache: bundler

rvm:
  - 2.0.0
  - 2.1
  - 2.2

env:
  - DB=sqlite

before_script:
  - gem install brakeman
  - cp config/local_env_travis.yml config/local_env.yml
  - bin/rake db:setup RAILS_ENV=test

script:
  - RAILS_ENV=test bin/rake --trace db:migrate test
  - brakeman -z -4
