sudo: false

language: ruby

cache: bundler

rvm:
  - 2.3.3

env:
  - DB=sqlite

before_script:
  - cp config/local_env_travis.yml config/local_env.yml
  - bundle exec rails version
  - RAILS_ENV=test bundle exec rails db:migrate
  - RAILS_ENV=test bundle exec rails db:migrate:status

script:
  - RAILS_ENV=test bundle exec rake --trace ci
  - RAILS_ENV=test bundle exec rails assets:precompile
  - gem install brakeman
  - brakeman -z -5
