# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38271f854bd61f3d39bd1b7079c135dcd314e8ce07a6910944f85e3c8bb5ac6c0171afb848f2e049a3c6c892c58480f0aa0b356929eafc7da3a53c7c91964a7f

test:
  secret_key_base: 86b34d537039bdac5de419d891610fc2a835379dfa0cfecb7ab3b0ef145ba7d3bba6c25986fbf4851202c3067e2d762d68c17ee82a99cbedfec7790ef7e994d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
